/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { RenderRequest } from '../models';
// @ts-ignore
import type { RenderResponse } from '../models';
/**
 * PromptRendersApi - axios parameter creator
 * @export
 */
export const PromptRendersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Renders the active \'live\' template version of a prompt using supplied variables.
         * @summary Render Live Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {RenderRequest} renderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renderLive: async (id: string, renderRequest: RenderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('renderLive', 'id', id)
            // verify required parameter 'renderRequest' is not null or undefined
            assertParamExists('renderLive', 'renderRequest', renderRequest)
            const localVarPath = `/v1/prompts/{id}/render`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(renderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Renders a specific template version of a prompt (even draft status) using supplied variables.
         * @summary Render Specific Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to render.
         * @param {RenderRequest} renderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renderVersion: async (id: string, version: string, renderRequest: RenderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('renderVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('renderVersion', 'version', version)
            // verify required parameter 'renderRequest' is not null or undefined
            assertParamExists('renderVersion', 'renderRequest', renderRequest)
            const localVarPath = `/v1/prompts/{id}/versions/{version}/render`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(renderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PromptRendersApi - functional programming interface
 * @export
 */
export const PromptRendersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PromptRendersApiAxiosParamCreator(configuration)
    return {
        /**
         * Renders the active \'live\' template version of a prompt using supplied variables.
         * @summary Render Live Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {RenderRequest} renderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renderLive(id: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RenderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.renderLive(id, renderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptRendersApi.renderLive']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Renders a specific template version of a prompt (even draft status) using supplied variables.
         * @summary Render Specific Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to render.
         * @param {RenderRequest} renderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renderVersion(id: string, version: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RenderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.renderVersion(id, version, renderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptRendersApi.renderVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PromptRendersApi - factory interface
 * @export
 */
export const PromptRendersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PromptRendersApiFp(configuration)
    return {
        /**
         * Renders the active \'live\' template version of a prompt using supplied variables.
         * @summary Render Live Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {RenderRequest} renderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renderLive(id: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig): AxiosPromise<RenderResponse> {
            return localVarFp.renderLive(id, renderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Renders a specific template version of a prompt (even draft status) using supplied variables.
         * @summary Render Specific Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to render.
         * @param {RenderRequest} renderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renderVersion(id: string, version: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig): AxiosPromise<RenderResponse> {
            return localVarFp.renderVersion(id, version, renderRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PromptRendersApi - interface
 * @export
 * @interface PromptRendersApi
 */
export interface PromptRendersApiInterface {
    /**
     * Renders the active \'live\' template version of a prompt using supplied variables.
     * @summary Render Live Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {RenderRequest} renderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptRendersApiInterface
     */
    renderLive(id: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig): AxiosPromise<RenderResponse>;

    /**
     * Renders a specific template version of a prompt (even draft status) using supplied variables.
     * @summary Render Specific Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to render.
     * @param {RenderRequest} renderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptRendersApiInterface
     */
    renderVersion(id: string, version: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig): AxiosPromise<RenderResponse>;

}

/**
 * PromptRendersApi - object-oriented interface
 * @export
 * @class PromptRendersApi
 * @extends {BaseAPI}
 */
export class PromptRendersApi extends BaseAPI implements PromptRendersApiInterface {
    /**
     * Renders the active \'live\' template version of a prompt using supplied variables.
     * @summary Render Live Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {RenderRequest} renderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptRendersApi
     */
    public renderLive(id: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig) {
        return PromptRendersApiFp(this.configuration).renderLive(id, renderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Renders a specific template version of a prompt (even draft status) using supplied variables.
     * @summary Render Specific Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to render.
     * @param {RenderRequest} renderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptRendersApi
     */
    public renderVersion(id: string, version: string, renderRequest: RenderRequest, options?: RawAxiosRequestConfig) {
        return PromptRendersApiFp(this.configuration).renderVersion(id, version, renderRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

