/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { CreatePrompt201Response } from '../models';
// @ts-ignore
import type { CreatePromptRequest } from '../models';
// @ts-ignore
import type { ListAllPrompts200Response } from '../models';
// @ts-ignore
import type { ListPrompts200Response } from '../models';
// @ts-ignore
import type { MovePromptRequest } from '../models';
// @ts-ignore
import type { UpdatePromptRequest } from '../models';
/**
 * PromptsApi - axios parameter creator
 * @export
 */
export const PromptsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Archives a specific prompt container, setting `status` to \'archived\'. The prompt still exists in the system and people can call it and use it, so a prompt is never deleted. Requires Org Admin or Team Admin privileges (GitHub repo owner model). Team Editors and Team Members are not authorized to archive prompts.
         * @summary Archive a Prompt
         * @param {string} id The unique UUID of the prompt to archive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        archivePrompt: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('archivePrompt', 'id', id)
            const localVarPath = `/v1/prompts/{id}/archive`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new prompt container.
         * @summary Create a Prompt
         * @param {string} teamID The ID of the team.
         * @param {CreatePromptRequest} createPromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPrompt: async (teamID: string, createPromptRequest: CreatePromptRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamID' is not null or undefined
            assertParamExists('createPrompt', 'teamID', teamID)
            // verify required parameter 'createPromptRequest' is not null or undefined
            assertParamExists('createPrompt', 'createPromptRequest', createPromptRequest)
            const localVarPath = `/v1/teams/{teamID}/prompts`
                .replace(`{${"teamID"}}`, encodeURIComponent(String(teamID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPromptRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns details of a specific prompt container by its unique UUID.
         * @summary Get a Prompt
         * @param {string} id The unique UUID of the prompt.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrompt: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPrompt', 'id', id)
            const localVarPath = `/v1/prompts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of prompts. If team_id query parameter is not provided, returns an empty list by default. Users can filter by a team they are a member of.
         * @summary List all prompts with team filter
         * @param {string} [teamId] Optional UUID of the team to filter prompts (alias of team).
         * @param {string} [team] Optional UUID of the team to filter prompts (alias of team_id).
         * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAllPrompts: async (teamId?: string, team?: string, archived?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/prompts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (teamId !== undefined) {
                localVarQueryParameter['team_id'] = teamId;
            }

            if (team !== undefined) {
                localVarQueryParameter['team'] = team;
            }

            if (archived !== undefined) {
                localVarQueryParameter['archived'] = archived;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists all available prompt containers.
         * @summary List Prompts
         * @param {string} teamID The ID of the team.
         * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPrompts: async (teamID: string, archived?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamID' is not null or undefined
            assertParamExists('listPrompts', 'teamID', teamID)
            const localVarPath = `/v1/teams/{teamID}/prompts`
                .replace(`{${"teamID"}}`, encodeURIComponent(String(teamID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (archived !== undefined) {
                localVarQueryParameter['archived'] = archived;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Moves a prompt from its current team to another team. Requires admin privileges on both teams.
         * @summary Move a Prompt
         * @param {string} id 
         * @param {MovePromptRequest} movePromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        movePrompt: async (id: string, movePromptRequest: MovePromptRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('movePrompt', 'id', id)
            // verify required parameter 'movePromptRequest' is not null or undefined
            assertParamExists('movePrompt', 'movePromptRequest', movePromptRequest)
            const localVarPath = `/v1/prompts/{id}/move`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(movePromptRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restores a previously archived prompt setting `status` back to \'active\'. Requires Team Admin or Org Admin.
         * @summary Restore a Prompt
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restorePrompt: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('restorePrompt', 'id', id)
            const localVarPath = `/v1/prompts/{id}/restore`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the description of a specific prompt by its unique UUID.
         * @summary Update a Prompt
         * @param {string} id The unique UUID of the prompt.
         * @param {UpdatePromptRequest} updatePromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePrompt: async (id: string, updatePromptRequest: UpdatePromptRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePrompt', 'id', id)
            // verify required parameter 'updatePromptRequest' is not null or undefined
            assertParamExists('updatePrompt', 'updatePromptRequest', updatePromptRequest)
            const localVarPath = `/v1/prompts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePromptRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PromptsApi - functional programming interface
 * @export
 */
export const PromptsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PromptsApiAxiosParamCreator(configuration)
    return {
        /**
         * Archives a specific prompt container, setting `status` to \'archived\'. The prompt still exists in the system and people can call it and use it, so a prompt is never deleted. Requires Org Admin or Team Admin privileges (GitHub repo owner model). Team Editors and Team Members are not authorized to archive prompts.
         * @summary Archive a Prompt
         * @param {string} id The unique UUID of the prompt to archive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async archivePrompt(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrompt201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.archivePrompt(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.archivePrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a new prompt container.
         * @summary Create a Prompt
         * @param {string} teamID The ID of the team.
         * @param {CreatePromptRequest} createPromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPrompt(teamID: string, createPromptRequest: CreatePromptRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrompt201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPrompt(teamID, createPromptRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.createPrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns details of a specific prompt container by its unique UUID.
         * @summary Get a Prompt
         * @param {string} id The unique UUID of the prompt.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPrompt(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrompt201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPrompt(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.getPrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a list of prompts. If team_id query parameter is not provided, returns an empty list by default. Users can filter by a team they are a member of.
         * @summary List all prompts with team filter
         * @param {string} [teamId] Optional UUID of the team to filter prompts (alias of team).
         * @param {string} [team] Optional UUID of the team to filter prompts (alias of team_id).
         * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAllPrompts(teamId?: string, team?: string, archived?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListAllPrompts200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAllPrompts(teamId, team, archived, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.listAllPrompts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists all available prompt containers.
         * @summary List Prompts
         * @param {string} teamID The ID of the team.
         * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPrompts(teamID: string, archived?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPrompts200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPrompts(teamID, archived, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.listPrompts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Moves a prompt from its current team to another team. Requires admin privileges on both teams.
         * @summary Move a Prompt
         * @param {string} id 
         * @param {MovePromptRequest} movePromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async movePrompt(id: string, movePromptRequest: MovePromptRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrompt201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.movePrompt(id, movePromptRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.movePrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Restores a previously archived prompt setting `status` back to \'active\'. Requires Team Admin or Org Admin.
         * @summary Restore a Prompt
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restorePrompt(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrompt201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restorePrompt(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.restorePrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the description of a specific prompt by its unique UUID.
         * @summary Update a Prompt
         * @param {string} id The unique UUID of the prompt.
         * @param {UpdatePromptRequest} updatePromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePrompt(id: string, updatePromptRequest: UpdatePromptRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrompt201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePrompt(id, updatePromptRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.updatePrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PromptsApi - factory interface
 * @export
 */
export const PromptsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PromptsApiFp(configuration)
    return {
        /**
         * Archives a specific prompt container, setting `status` to \'archived\'. The prompt still exists in the system and people can call it and use it, so a prompt is never deleted. Requires Org Admin or Team Admin privileges (GitHub repo owner model). Team Editors and Team Members are not authorized to archive prompts.
         * @summary Archive a Prompt
         * @param {string} id The unique UUID of the prompt to archive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        archivePrompt(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response> {
            return localVarFp.archivePrompt(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new prompt container.
         * @summary Create a Prompt
         * @param {string} teamID The ID of the team.
         * @param {CreatePromptRequest} createPromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPrompt(teamID: string, createPromptRequest: CreatePromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response> {
            return localVarFp.createPrompt(teamID, createPromptRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns details of a specific prompt container by its unique UUID.
         * @summary Get a Prompt
         * @param {string} id The unique UUID of the prompt.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrompt(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response> {
            return localVarFp.getPrompt(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of prompts. If team_id query parameter is not provided, returns an empty list by default. Users can filter by a team they are a member of.
         * @summary List all prompts with team filter
         * @param {string} [teamId] Optional UUID of the team to filter prompts (alias of team).
         * @param {string} [team] Optional UUID of the team to filter prompts (alias of team_id).
         * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAllPrompts(teamId?: string, team?: string, archived?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListAllPrompts200Response> {
            return localVarFp.listAllPrompts(teamId, team, archived, options).then((request) => request(axios, basePath));
        },
        /**
         * Lists all available prompt containers.
         * @summary List Prompts
         * @param {string} teamID The ID of the team.
         * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPrompts(teamID: string, archived?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListPrompts200Response> {
            return localVarFp.listPrompts(teamID, archived, options).then((request) => request(axios, basePath));
        },
        /**
         * Moves a prompt from its current team to another team. Requires admin privileges on both teams.
         * @summary Move a Prompt
         * @param {string} id 
         * @param {MovePromptRequest} movePromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        movePrompt(id: string, movePromptRequest: MovePromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response> {
            return localVarFp.movePrompt(id, movePromptRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Restores a previously archived prompt setting `status` back to \'active\'. Requires Team Admin or Org Admin.
         * @summary Restore a Prompt
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restorePrompt(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response> {
            return localVarFp.restorePrompt(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the description of a specific prompt by its unique UUID.
         * @summary Update a Prompt
         * @param {string} id The unique UUID of the prompt.
         * @param {UpdatePromptRequest} updatePromptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePrompt(id: string, updatePromptRequest: UpdatePromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response> {
            return localVarFp.updatePrompt(id, updatePromptRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PromptsApi - interface
 * @export
 * @interface PromptsApi
 */
export interface PromptsApiInterface {
    /**
     * Archives a specific prompt container, setting `status` to \'archived\'. The prompt still exists in the system and people can call it and use it, so a prompt is never deleted. Requires Org Admin or Team Admin privileges (GitHub repo owner model). Team Editors and Team Members are not authorized to archive prompts.
     * @summary Archive a Prompt
     * @param {string} id The unique UUID of the prompt to archive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    archivePrompt(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response>;

    /**
     * Creates a new prompt container.
     * @summary Create a Prompt
     * @param {string} teamID The ID of the team.
     * @param {CreatePromptRequest} createPromptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    createPrompt(teamID: string, createPromptRequest: CreatePromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response>;

    /**
     * Returns details of a specific prompt container by its unique UUID.
     * @summary Get a Prompt
     * @param {string} id The unique UUID of the prompt.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    getPrompt(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response>;

    /**
     * Returns a list of prompts. If team_id query parameter is not provided, returns an empty list by default. Users can filter by a team they are a member of.
     * @summary List all prompts with team filter
     * @param {string} [teamId] Optional UUID of the team to filter prompts (alias of team).
     * @param {string} [team] Optional UUID of the team to filter prompts (alias of team_id).
     * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    listAllPrompts(teamId?: string, team?: string, archived?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListAllPrompts200Response>;

    /**
     * Lists all available prompt containers.
     * @summary List Prompts
     * @param {string} teamID The ID of the team.
     * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    listPrompts(teamID: string, archived?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListPrompts200Response>;

    /**
     * Moves a prompt from its current team to another team. Requires admin privileges on both teams.
     * @summary Move a Prompt
     * @param {string} id 
     * @param {MovePromptRequest} movePromptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    movePrompt(id: string, movePromptRequest: MovePromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response>;

    /**
     * Restores a previously archived prompt setting `status` back to \'active\'. Requires Team Admin or Org Admin.
     * @summary Restore a Prompt
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    restorePrompt(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response>;

    /**
     * Updates the description of a specific prompt by its unique UUID.
     * @summary Update a Prompt
     * @param {string} id The unique UUID of the prompt.
     * @param {UpdatePromptRequest} updatePromptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApiInterface
     */
    updatePrompt(id: string, updatePromptRequest: UpdatePromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrompt201Response>;

}

/**
 * PromptsApi - object-oriented interface
 * @export
 * @class PromptsApi
 * @extends {BaseAPI}
 */
export class PromptsApi extends BaseAPI implements PromptsApiInterface {
    /**
     * Archives a specific prompt container, setting `status` to \'archived\'. The prompt still exists in the system and people can call it and use it, so a prompt is never deleted. Requires Org Admin or Team Admin privileges (GitHub repo owner model). Team Editors and Team Members are not authorized to archive prompts.
     * @summary Archive a Prompt
     * @param {string} id The unique UUID of the prompt to archive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public archivePrompt(id: string, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).archivePrompt(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a new prompt container.
     * @summary Create a Prompt
     * @param {string} teamID The ID of the team.
     * @param {CreatePromptRequest} createPromptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public createPrompt(teamID: string, createPromptRequest: CreatePromptRequest, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).createPrompt(teamID, createPromptRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns details of a specific prompt container by its unique UUID.
     * @summary Get a Prompt
     * @param {string} id The unique UUID of the prompt.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public getPrompt(id: string, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).getPrompt(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of prompts. If team_id query parameter is not provided, returns an empty list by default. Users can filter by a team they are a member of.
     * @summary List all prompts with team filter
     * @param {string} [teamId] Optional UUID of the team to filter prompts (alias of team).
     * @param {string} [team] Optional UUID of the team to filter prompts (alias of team_id).
     * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public listAllPrompts(teamId?: string, team?: string, archived?: boolean, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).listAllPrompts(teamId, team, archived, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists all available prompt containers.
     * @summary List Prompts
     * @param {string} teamID The ID of the team.
     * @param {boolean} [archived] Optional boolean to filter prompts by archive state.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public listPrompts(teamID: string, archived?: boolean, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).listPrompts(teamID, archived, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Moves a prompt from its current team to another team. Requires admin privileges on both teams.
     * @summary Move a Prompt
     * @param {string} id 
     * @param {MovePromptRequest} movePromptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public movePrompt(id: string, movePromptRequest: MovePromptRequest, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).movePrompt(id, movePromptRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Restores a previously archived prompt setting `status` back to \'active\'. Requires Team Admin or Org Admin.
     * @summary Restore a Prompt
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public restorePrompt(id: string, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).restorePrompt(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the description of a specific prompt by its unique UUID.
     * @summary Update a Prompt
     * @param {string} id The unique UUID of the prompt.
     * @param {UpdatePromptRequest} updatePromptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptsApi
     */
    public updatePrompt(id: string, updatePromptRequest: UpdatePromptRequest, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).updatePrompt(id, updatePromptRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

