/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { CreateVersion201Response } from '../models';
// @ts-ignore
import type { CreateVersionRequest } from '../models';
// @ts-ignore
import type { DiffVersions200Response } from '../models';
// @ts-ignore
import type { ListVersionTags200Response } from '../models';
// @ts-ignore
import type { ListVersions200Response } from '../models';
// @ts-ignore
import type { SetVersionTagRequest } from '../models';
// @ts-ignore
import type { UpdateVersionRequest } from '../models';
/**
 * PromptVersionsApi - axios parameter creator
 * @export
 */
export const PromptVersionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Archives a prompt version, marking its status as archived.
         * @summary Archive Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to archive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        archiveVersion: async (id: string, version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('archiveVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('archiveVersion', 'version', version)
            const localVarPath = `/v1/prompts/{id}/versions/{version}/archive`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new version of the prompt template in \'draft\' state.
         * @summary Create a Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {CreateVersionRequest} createVersionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVersion: async (id: string, createVersionRequest: CreateVersionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createVersion', 'id', id)
            // verify required parameter 'createVersionRequest' is not null or undefined
            assertParamExists('createVersion', 'createVersionRequest', createVersionRequest)
            const localVarPath = `/v1/prompts/{id}/versions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createVersionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a specific prompt template version. Only versions currently in the \'draft\' status may be deleted. 
         * @summary Delete Prompt Version Draft
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePromptVersion: async (id: string, version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePromptVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('deletePromptVersion', 'version', version)
            const localVarPath = `/v1/prompts/{id}/versions/{version}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Demotes a live prompt version to stable (making it inactive but remaining read-only).
         * @summary Demote Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to demote.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        demoteVersion: async (id: string, version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('demoteVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('demoteVersion', 'version', version)
            const localVarPath = `/v1/prompts/{id}/versions/{version}/demote`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Compares the templates of two prompt versions side-by-side and returns a unified diff. Requires read access to the prompt.
         * @summary Diff Prompt Versions
         * @param {string} id 
         * @param {number} from The source version number to compare from.
         * @param {number} to The target version number to compare to.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diffVersions: async (id: string, from: number, to: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('diffVersions', 'id', id)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('diffVersions', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('diffVersions', 'to', to)
            const localVarPath = `/v1/prompts/{id}/versions/diff`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Copies the specified prompt version\'s template to create a new prompt version in draft state. This operation does not copy any associated payloads, only the prompt template and other metadata. 
         * @summary Duplicate Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to duplicate from.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        duplicateVersion: async (id: string, version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('duplicateVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('duplicateVersion', 'version', version)
            const localVarPath = `/v1/prompts/{id}/versions/{version}/duplicate`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves details of a specific prompt template version by version number.
         * @summary Get Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVersion: async (id: string, version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('getVersion', 'version', version)
            const localVarPath = `/v1/prompts/{id}/versions/{version}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists all tags associated with versions of this prompt.
         * @summary List Prompt Version Tags
         * @param {string} id Unique prompt UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVersionTags: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listVersionTags', 'id', id)
            const localVarPath = `/v1/prompts/{id}/tags`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists all template versions associated with a prompt container.
         * @summary List Prompt Versions
         * @param {string} id Unique prompt UUID.
         * @param {string} [tags] Optional comma-separated list of tags to filter prompt versions.
         * @param {ListVersionsStatusEnum} [status] Optional status to filter prompt versions by (draft, live, archived).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVersions: async (id: string, tags?: string, status?: ListVersionsStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listVersions', 'id', id)
            const localVarPath = `/v1/prompts/{id}/versions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (tags !== undefined) {
                localVarQueryParameter['tags'] = tags;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Promotes a version of the prompt template along the lifecycle: draft -> stable -> live. Promoting from draft makes it stable (read-only). Promoting from stable makes it live. When promoting a version to live, any previous live version is demoted to stable. 
         * @summary Promote Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to promote.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        promoteVersion: async (id: string, version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('promoteVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('promoteVersion', 'version', version)
            const localVarPath = `/v1/prompts/{id}/versions/{version}/promote`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes/deletes the specified version tag from the prompt.
         * @summary Remove Version Tag
         * @param {string} id Unique prompt UUID.
         * @param {string} tag Tag string to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeVersionTag: async (id: string, tag: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('removeVersionTag', 'id', id)
            // verify required parameter 'tag' is not null or undefined
            assertParamExists('removeVersionTag', 'tag', tag)
            const localVarPath = `/v1/prompts/{id}/tags/{tag}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"tag"}}`, encodeURIComponent(String(tag)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Attaches a unique string tag (e.g. \'prod\') to the specified prompt version, replacing the tag on any other version of this prompt if it was already assigned.
         * @summary Attach/Set Version Tag
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to tag.
         * @param {SetVersionTagRequest} setVersionTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setVersionTag: async (id: string, version: string, setVersionTagRequest: SetVersionTagRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('setVersionTag', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('setVersionTag', 'version', version)
            // verify required parameter 'setVersionTagRequest' is not null or undefined
            assertParamExists('setVersionTag', 'setVersionTagRequest', setVersionTagRequest)
            const localVarPath = `/v1/prompts/{id}/versions/{version}/tags`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setVersionTagRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the draft template code of a specific version. Only versions currently in the \'draft\' status may be modified. 
         * @summary Update Prompt Version Draft
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to update.
         * @param {UpdateVersionRequest} updateVersionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVersion: async (id: string, version: string, updateVersionRequest: UpdateVersionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('updateVersion', 'version', version)
            // verify required parameter 'updateVersionRequest' is not null or undefined
            assertParamExists('updateVersion', 'updateVersionRequest', updateVersionRequest)
            const localVarPath = `/v1/prompts/{id}/versions/{version}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateVersionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PromptVersionsApi - functional programming interface
 * @export
 */
export const PromptVersionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PromptVersionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Archives a prompt version, marking its status as archived.
         * @summary Archive Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to archive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async archiveVersion(id: string, version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.archiveVersion(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.archiveVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a new version of the prompt template in \'draft\' state.
         * @summary Create a Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {CreateVersionRequest} createVersionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVersion(id: string, createVersionRequest: CreateVersionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVersion(id, createVersionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.createVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a specific prompt template version. Only versions currently in the \'draft\' status may be deleted. 
         * @summary Delete Prompt Version Draft
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePromptVersion(id: string, version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePromptVersion(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.deletePromptVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Demotes a live prompt version to stable (making it inactive but remaining read-only).
         * @summary Demote Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to demote.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async demoteVersion(id: string, version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.demoteVersion(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.demoteVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Compares the templates of two prompt versions side-by-side and returns a unified diff. Requires read access to the prompt.
         * @summary Diff Prompt Versions
         * @param {string} id 
         * @param {number} from The source version number to compare from.
         * @param {number} to The target version number to compare to.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async diffVersions(id: string, from: number, to: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DiffVersions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.diffVersions(id, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.diffVersions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Copies the specified prompt version\'s template to create a new prompt version in draft state. This operation does not copy any associated payloads, only the prompt template and other metadata. 
         * @summary Duplicate Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to duplicate from.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async duplicateVersion(id: string, version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.duplicateVersion(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.duplicateVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves details of a specific prompt template version by version number.
         * @summary Get Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVersion(id: string, version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVersion(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.getVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists all tags associated with versions of this prompt.
         * @summary List Prompt Version Tags
         * @param {string} id Unique prompt UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVersionTags(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListVersionTags200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVersionTags(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.listVersionTags']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists all template versions associated with a prompt container.
         * @summary List Prompt Versions
         * @param {string} id Unique prompt UUID.
         * @param {string} [tags] Optional comma-separated list of tags to filter prompt versions.
         * @param {ListVersionsStatusEnum} [status] Optional status to filter prompt versions by (draft, live, archived).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVersions(id: string, tags?: string, status?: ListVersionsStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListVersions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVersions(id, tags, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.listVersions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Promotes a version of the prompt template along the lifecycle: draft -> stable -> live. Promoting from draft makes it stable (read-only). Promoting from stable makes it live. When promoting a version to live, any previous live version is demoted to stable. 
         * @summary Promote Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to promote.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async promoteVersion(id: string, version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.promoteVersion(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.promoteVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Removes/deletes the specified version tag from the prompt.
         * @summary Remove Version Tag
         * @param {string} id Unique prompt UUID.
         * @param {string} tag Tag string to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeVersionTag(id: string, tag: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeVersionTag(id, tag, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.removeVersionTag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Attaches a unique string tag (e.g. \'prod\') to the specified prompt version, replacing the tag on any other version of this prompt if it was already assigned.
         * @summary Attach/Set Version Tag
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to tag.
         * @param {SetVersionTagRequest} setVersionTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setVersionTag(id: string, version: string, setVersionTagRequest: SetVersionTagRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setVersionTag(id, version, setVersionTagRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.setVersionTag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the draft template code of a specific version. Only versions currently in the \'draft\' status may be modified. 
         * @summary Update Prompt Version Draft
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to update.
         * @param {UpdateVersionRequest} updateVersionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVersion(id: string, version: string, updateVersionRequest: UpdateVersionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVersion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateVersion(id, version, updateVersionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptVersionsApi.updateVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PromptVersionsApi - factory interface
 * @export
 */
export const PromptVersionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PromptVersionsApiFp(configuration)
    return {
        /**
         * Archives a prompt version, marking its status as archived.
         * @summary Archive Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to archive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        archiveVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.archiveVersion(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new version of the prompt template in \'draft\' state.
         * @summary Create a Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {CreateVersionRequest} createVersionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVersion(id: string, createVersionRequest: CreateVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.createVersion(id, createVersionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a specific prompt template version. Only versions currently in the \'draft\' status may be deleted. 
         * @summary Delete Prompt Version Draft
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePromptVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePromptVersion(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * Demotes a live prompt version to stable (making it inactive but remaining read-only).
         * @summary Demote Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to demote.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        demoteVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.demoteVersion(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * Compares the templates of two prompt versions side-by-side and returns a unified diff. Requires read access to the prompt.
         * @summary Diff Prompt Versions
         * @param {string} id 
         * @param {number} from The source version number to compare from.
         * @param {number} to The target version number to compare to.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diffVersions(id: string, from: number, to: number, options?: RawAxiosRequestConfig): AxiosPromise<DiffVersions200Response> {
            return localVarFp.diffVersions(id, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * Copies the specified prompt version\'s template to create a new prompt version in draft state. This operation does not copy any associated payloads, only the prompt template and other metadata. 
         * @summary Duplicate Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to duplicate from.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        duplicateVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.duplicateVersion(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves details of a specific prompt template version by version number.
         * @summary Get Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.getVersion(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * Lists all tags associated with versions of this prompt.
         * @summary List Prompt Version Tags
         * @param {string} id Unique prompt UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVersionTags(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ListVersionTags200Response> {
            return localVarFp.listVersionTags(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Lists all template versions associated with a prompt container.
         * @summary List Prompt Versions
         * @param {string} id Unique prompt UUID.
         * @param {string} [tags] Optional comma-separated list of tags to filter prompt versions.
         * @param {ListVersionsStatusEnum} [status] Optional status to filter prompt versions by (draft, live, archived).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVersions(id: string, tags?: string, status?: ListVersionsStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<ListVersions200Response> {
            return localVarFp.listVersions(id, tags, status, options).then((request) => request(axios, basePath));
        },
        /**
         * Promotes a version of the prompt template along the lifecycle: draft -> stable -> live. Promoting from draft makes it stable (read-only). Promoting from stable makes it live. When promoting a version to live, any previous live version is demoted to stable. 
         * @summary Promote Prompt Version
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to promote.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        promoteVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.promoteVersion(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes/deletes the specified version tag from the prompt.
         * @summary Remove Version Tag
         * @param {string} id Unique prompt UUID.
         * @param {string} tag Tag string to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeVersionTag(id: string, tag: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeVersionTag(id, tag, options).then((request) => request(axios, basePath));
        },
        /**
         * Attaches a unique string tag (e.g. \'prod\') to the specified prompt version, replacing the tag on any other version of this prompt if it was already assigned.
         * @summary Attach/Set Version Tag
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to tag.
         * @param {SetVersionTagRequest} setVersionTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setVersionTag(id: string, version: string, setVersionTagRequest: SetVersionTagRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.setVersionTag(id, version, setVersionTagRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the draft template code of a specific version. Only versions currently in the \'draft\' status may be modified. 
         * @summary Update Prompt Version Draft
         * @param {string} id Unique prompt UUID.
         * @param {string} version Version sequence number (integer) or version tag (string) to update.
         * @param {UpdateVersionRequest} updateVersionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVersion(id: string, version: string, updateVersionRequest: UpdateVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response> {
            return localVarFp.updateVersion(id, version, updateVersionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PromptVersionsApi - interface
 * @export
 * @interface PromptVersionsApi
 */
export interface PromptVersionsApiInterface {
    /**
     * Archives a prompt version, marking its status as archived.
     * @summary Archive Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to archive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    archiveVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

    /**
     * Creates a new version of the prompt template in \'draft\' state.
     * @summary Create a Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {CreateVersionRequest} createVersionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    createVersion(id: string, createVersionRequest: CreateVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

    /**
     * Deletes a specific prompt template version. Only versions currently in the \'draft\' status may be deleted. 
     * @summary Delete Prompt Version Draft
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    deletePromptVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Demotes a live prompt version to stable (making it inactive but remaining read-only).
     * @summary Demote Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to demote.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    demoteVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

    /**
     * Compares the templates of two prompt versions side-by-side and returns a unified diff. Requires read access to the prompt.
     * @summary Diff Prompt Versions
     * @param {string} id 
     * @param {number} from The source version number to compare from.
     * @param {number} to The target version number to compare to.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    diffVersions(id: string, from: number, to: number, options?: RawAxiosRequestConfig): AxiosPromise<DiffVersions200Response>;

    /**
     * Copies the specified prompt version\'s template to create a new prompt version in draft state. This operation does not copy any associated payloads, only the prompt template and other metadata. 
     * @summary Duplicate Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to duplicate from.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    duplicateVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

    /**
     * Retrieves details of a specific prompt template version by version number.
     * @summary Get Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    getVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

    /**
     * Lists all tags associated with versions of this prompt.
     * @summary List Prompt Version Tags
     * @param {string} id Unique prompt UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    listVersionTags(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ListVersionTags200Response>;

    /**
     * Lists all template versions associated with a prompt container.
     * @summary List Prompt Versions
     * @param {string} id Unique prompt UUID.
     * @param {string} [tags] Optional comma-separated list of tags to filter prompt versions.
     * @param {ListVersionsStatusEnum} [status] Optional status to filter prompt versions by (draft, live, archived).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    listVersions(id: string, tags?: string, status?: ListVersionsStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<ListVersions200Response>;

    /**
     * Promotes a version of the prompt template along the lifecycle: draft -> stable -> live. Promoting from draft makes it stable (read-only). Promoting from stable makes it live. When promoting a version to live, any previous live version is demoted to stable. 
     * @summary Promote Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to promote.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    promoteVersion(id: string, version: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

    /**
     * Removes/deletes the specified version tag from the prompt.
     * @summary Remove Version Tag
     * @param {string} id Unique prompt UUID.
     * @param {string} tag Tag string to remove.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    removeVersionTag(id: string, tag: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Attaches a unique string tag (e.g. \'prod\') to the specified prompt version, replacing the tag on any other version of this prompt if it was already assigned.
     * @summary Attach/Set Version Tag
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to tag.
     * @param {SetVersionTagRequest} setVersionTagRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    setVersionTag(id: string, version: string, setVersionTagRequest: SetVersionTagRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

    /**
     * Updates the draft template code of a specific version. Only versions currently in the \'draft\' status may be modified. 
     * @summary Update Prompt Version Draft
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to update.
     * @param {UpdateVersionRequest} updateVersionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApiInterface
     */
    updateVersion(id: string, version: string, updateVersionRequest: UpdateVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateVersion201Response>;

}

/**
 * PromptVersionsApi - object-oriented interface
 * @export
 * @class PromptVersionsApi
 * @extends {BaseAPI}
 */
export class PromptVersionsApi extends BaseAPI implements PromptVersionsApiInterface {
    /**
     * Archives a prompt version, marking its status as archived.
     * @summary Archive Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to archive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public archiveVersion(id: string, version: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).archiveVersion(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a new version of the prompt template in \'draft\' state.
     * @summary Create a Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {CreateVersionRequest} createVersionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public createVersion(id: string, createVersionRequest: CreateVersionRequest, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).createVersion(id, createVersionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a specific prompt template version. Only versions currently in the \'draft\' status may be deleted. 
     * @summary Delete Prompt Version Draft
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public deletePromptVersion(id: string, version: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).deletePromptVersion(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Demotes a live prompt version to stable (making it inactive but remaining read-only).
     * @summary Demote Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to demote.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public demoteVersion(id: string, version: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).demoteVersion(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Compares the templates of two prompt versions side-by-side and returns a unified diff. Requires read access to the prompt.
     * @summary Diff Prompt Versions
     * @param {string} id 
     * @param {number} from The source version number to compare from.
     * @param {number} to The target version number to compare to.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public diffVersions(id: string, from: number, to: number, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).diffVersions(id, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Copies the specified prompt version\'s template to create a new prompt version in draft state. This operation does not copy any associated payloads, only the prompt template and other metadata. 
     * @summary Duplicate Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to duplicate from.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public duplicateVersion(id: string, version: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).duplicateVersion(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves details of a specific prompt template version by version number.
     * @summary Get Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public getVersion(id: string, version: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).getVersion(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists all tags associated with versions of this prompt.
     * @summary List Prompt Version Tags
     * @param {string} id Unique prompt UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public listVersionTags(id: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).listVersionTags(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists all template versions associated with a prompt container.
     * @summary List Prompt Versions
     * @param {string} id Unique prompt UUID.
     * @param {string} [tags] Optional comma-separated list of tags to filter prompt versions.
     * @param {ListVersionsStatusEnum} [status] Optional status to filter prompt versions by (draft, live, archived).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public listVersions(id: string, tags?: string, status?: ListVersionsStatusEnum, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).listVersions(id, tags, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Promotes a version of the prompt template along the lifecycle: draft -> stable -> live. Promoting from draft makes it stable (read-only). Promoting from stable makes it live. When promoting a version to live, any previous live version is demoted to stable. 
     * @summary Promote Prompt Version
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to promote.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public promoteVersion(id: string, version: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).promoteVersion(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes/deletes the specified version tag from the prompt.
     * @summary Remove Version Tag
     * @param {string} id Unique prompt UUID.
     * @param {string} tag Tag string to remove.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public removeVersionTag(id: string, tag: string, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).removeVersionTag(id, tag, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Attaches a unique string tag (e.g. \'prod\') to the specified prompt version, replacing the tag on any other version of this prompt if it was already assigned.
     * @summary Attach/Set Version Tag
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to tag.
     * @param {SetVersionTagRequest} setVersionTagRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public setVersionTag(id: string, version: string, setVersionTagRequest: SetVersionTagRequest, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).setVersionTag(id, version, setVersionTagRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the draft template code of a specific version. Only versions currently in the \'draft\' status may be modified. 
     * @summary Update Prompt Version Draft
     * @param {string} id Unique prompt UUID.
     * @param {string} version Version sequence number (integer) or version tag (string) to update.
     * @param {UpdateVersionRequest} updateVersionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptVersionsApi
     */
    public updateVersion(id: string, version: string, updateVersionRequest: UpdateVersionRequest, options?: RawAxiosRequestConfig) {
        return PromptVersionsApiFp(this.configuration).updateVersion(id, version, updateVersionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ListVersionsStatusEnum = {
    Draft: 'draft',
    Live: 'live',
    Archived: 'archived'
} as const;
export type ListVersionsStatusEnum = typeof ListVersionsStatusEnum[keyof typeof ListVersionsStatusEnum];
