/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { CreatePromptPayload201Response } from '../models';
// @ts-ignore
import type { CreatePromptPayloadRequest } from '../models';
// @ts-ignore
import type { ListPromptPayloads200Response } from '../models';
// @ts-ignore
import type { UpdatePromptPayloadRequest } from '../models';
/**
 * PromptPayloadsApi - axios parameter creator
 * @export
 */
export const PromptPayloadsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new sample payload for the specified prompt. Only editors of the team can create.
         * @summary Create a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {CreatePromptPayloadRequest} createPromptPayloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPromptPayload: async (id: string, createPromptPayloadRequest: CreatePromptPayloadRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createPromptPayload', 'id', id)
            // verify required parameter 'createPromptPayloadRequest' is not null or undefined
            assertParamExists('createPromptPayload', 'createPromptPayloadRequest', createPromptPayloadRequest)
            const localVarPath = `/v1/prompts/{id}/payloads`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPromptPayloadRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a specific sample payload. Only editors can delete.
         * @summary Delete a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePromptPayload: async (id: string, payloadID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePromptPayload', 'id', id)
            // verify required parameter 'payloadID' is not null or undefined
            assertParamExists('deletePromptPayload', 'payloadID', payloadID)
            const localVarPath = `/v1/prompts/{id}/payloads/{payloadID}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"payloadID"}}`, encodeURIComponent(String(payloadID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a specific sample payload by its ID and prompt ID.
         * @summary Get a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPromptPayload: async (id: string, payloadID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPromptPayload', 'id', id)
            // verify required parameter 'payloadID' is not null or undefined
            assertParamExists('getPromptPayload', 'payloadID', payloadID)
            const localVarPath = `/v1/prompts/{id}/payloads/{payloadID}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"payloadID"}}`, encodeURIComponent(String(payloadID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists all sample payloads associated with the specified prompt.
         * @summary List Prompt Payloads
         * @param {string} id Unique prompt UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPromptPayloads: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listPromptPayloads', 'id', id)
            const localVarPath = `/v1/prompts/{id}/payloads`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates an existing sample payload\'s variables and/or optional name. Only editors can update.
         * @summary Update a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {UpdatePromptPayloadRequest} updatePromptPayloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePromptPayload: async (id: string, payloadID: string, updatePromptPayloadRequest: UpdatePromptPayloadRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePromptPayload', 'id', id)
            // verify required parameter 'payloadID' is not null or undefined
            assertParamExists('updatePromptPayload', 'payloadID', payloadID)
            // verify required parameter 'updatePromptPayloadRequest' is not null or undefined
            assertParamExists('updatePromptPayload', 'updatePromptPayloadRequest', updatePromptPayloadRequest)
            const localVarPath = `/v1/prompts/{id}/payloads/{payloadID}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"payloadID"}}`, encodeURIComponent(String(payloadID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePromptPayloadRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PromptPayloadsApi - functional programming interface
 * @export
 */
export const PromptPayloadsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PromptPayloadsApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new sample payload for the specified prompt. Only editors of the team can create.
         * @summary Create a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {CreatePromptPayloadRequest} createPromptPayloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPromptPayload(id: string, createPromptPayloadRequest: CreatePromptPayloadRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePromptPayload201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPromptPayload(id, createPromptPayloadRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptPayloadsApi.createPromptPayload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a specific sample payload. Only editors can delete.
         * @summary Delete a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePromptPayload(id, payloadID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptPayloadsApi.deletePromptPayload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a specific sample payload by its ID and prompt ID.
         * @summary Get a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePromptPayload201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPromptPayload(id, payloadID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptPayloadsApi.getPromptPayload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists all sample payloads associated with the specified prompt.
         * @summary List Prompt Payloads
         * @param {string} id Unique prompt UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPromptPayloads(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPromptPayloads200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPromptPayloads(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptPayloadsApi.listPromptPayloads']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates an existing sample payload\'s variables and/or optional name. Only editors can update.
         * @summary Update a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {UpdatePromptPayloadRequest} updatePromptPayloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePromptPayload(id: string, payloadID: string, updatePromptPayloadRequest: UpdatePromptPayloadRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePromptPayload201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePromptPayload(id, payloadID, updatePromptPayloadRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptPayloadsApi.updatePromptPayload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PromptPayloadsApi - factory interface
 * @export
 */
export const PromptPayloadsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PromptPayloadsApiFp(configuration)
    return {
        /**
         * Creates a new sample payload for the specified prompt. Only editors of the team can create.
         * @summary Create a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {CreatePromptPayloadRequest} createPromptPayloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPromptPayload(id: string, createPromptPayloadRequest: CreatePromptPayloadRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePromptPayload201Response> {
            return localVarFp.createPromptPayload(id, createPromptPayloadRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a specific sample payload. Only editors can delete.
         * @summary Delete a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePromptPayload(id, payloadID, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a specific sample payload by its ID and prompt ID.
         * @summary Get a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePromptPayload201Response> {
            return localVarFp.getPromptPayload(id, payloadID, options).then((request) => request(axios, basePath));
        },
        /**
         * Lists all sample payloads associated with the specified prompt.
         * @summary List Prompt Payloads
         * @param {string} id Unique prompt UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPromptPayloads(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ListPromptPayloads200Response> {
            return localVarFp.listPromptPayloads(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates an existing sample payload\'s variables and/or optional name. Only editors can update.
         * @summary Update a Prompt Payload
         * @param {string} id Unique prompt UUID.
         * @param {string} payloadID Unique payload UUID.
         * @param {UpdatePromptPayloadRequest} updatePromptPayloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePromptPayload(id: string, payloadID: string, updatePromptPayloadRequest: UpdatePromptPayloadRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePromptPayload201Response> {
            return localVarFp.updatePromptPayload(id, payloadID, updatePromptPayloadRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PromptPayloadsApi - interface
 * @export
 * @interface PromptPayloadsApi
 */
export interface PromptPayloadsApiInterface {
    /**
     * Creates a new sample payload for the specified prompt. Only editors of the team can create.
     * @summary Create a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {CreatePromptPayloadRequest} createPromptPayloadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApiInterface
     */
    createPromptPayload(id: string, createPromptPayloadRequest: CreatePromptPayloadRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePromptPayload201Response>;

    /**
     * Deletes a specific sample payload. Only editors can delete.
     * @summary Delete a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {string} payloadID Unique payload UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApiInterface
     */
    deletePromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Retrieves a specific sample payload by its ID and prompt ID.
     * @summary Get a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {string} payloadID Unique payload UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApiInterface
     */
    getPromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig): AxiosPromise<CreatePromptPayload201Response>;

    /**
     * Lists all sample payloads associated with the specified prompt.
     * @summary List Prompt Payloads
     * @param {string} id Unique prompt UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApiInterface
     */
    listPromptPayloads(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ListPromptPayloads200Response>;

    /**
     * Updates an existing sample payload\'s variables and/or optional name. Only editors can update.
     * @summary Update a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {string} payloadID Unique payload UUID.
     * @param {UpdatePromptPayloadRequest} updatePromptPayloadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApiInterface
     */
    updatePromptPayload(id: string, payloadID: string, updatePromptPayloadRequest: UpdatePromptPayloadRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePromptPayload201Response>;

}

/**
 * PromptPayloadsApi - object-oriented interface
 * @export
 * @class PromptPayloadsApi
 * @extends {BaseAPI}
 */
export class PromptPayloadsApi extends BaseAPI implements PromptPayloadsApiInterface {
    /**
     * Creates a new sample payload for the specified prompt. Only editors of the team can create.
     * @summary Create a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {CreatePromptPayloadRequest} createPromptPayloadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApi
     */
    public createPromptPayload(id: string, createPromptPayloadRequest: CreatePromptPayloadRequest, options?: RawAxiosRequestConfig) {
        return PromptPayloadsApiFp(this.configuration).createPromptPayload(id, createPromptPayloadRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a specific sample payload. Only editors can delete.
     * @summary Delete a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {string} payloadID Unique payload UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApi
     */
    public deletePromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig) {
        return PromptPayloadsApiFp(this.configuration).deletePromptPayload(id, payloadID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a specific sample payload by its ID and prompt ID.
     * @summary Get a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {string} payloadID Unique payload UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApi
     */
    public getPromptPayload(id: string, payloadID: string, options?: RawAxiosRequestConfig) {
        return PromptPayloadsApiFp(this.configuration).getPromptPayload(id, payloadID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists all sample payloads associated with the specified prompt.
     * @summary List Prompt Payloads
     * @param {string} id Unique prompt UUID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApi
     */
    public listPromptPayloads(id: string, options?: RawAxiosRequestConfig) {
        return PromptPayloadsApiFp(this.configuration).listPromptPayloads(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates an existing sample payload\'s variables and/or optional name. Only editors can update.
     * @summary Update a Prompt Payload
     * @param {string} id Unique prompt UUID.
     * @param {string} payloadID Unique payload UUID.
     * @param {UpdatePromptPayloadRequest} updatePromptPayloadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromptPayloadsApi
     */
    public updatePromptPayload(id: string, payloadID: string, updatePromptPayloadRequest: UpdatePromptPayloadRequest, options?: RawAxiosRequestConfig) {
        return PromptPayloadsApiFp(this.configuration).updatePromptPayload(id, payloadID, updatePromptPayloadRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

