/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { AddTeamMemberRequest } from '../models';
// @ts-ignore
import type { GetAdminInbox200Response } from '../models';
// @ts-ignore
import type { ListTeamMembers200Response } from '../models';
// @ts-ignore
import type { ResolveJoinRequestRequest } from '../models';
// @ts-ignore
import type { TeamJoinRequest } from '../models';
// @ts-ignore
import type { UpdateTeamMemberRole200Response } from '../models';
// @ts-ignore
import type { UpdateTeamMemberRoleRequest } from '../models';
/**
 * TeamMembershipsApi - axios parameter creator
 * @export
 */
export const TeamMembershipsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Adds a user to a team. Requires admin privileges.
         * @summary Add Team Member
         * @param {string} id 
         * @param {AddTeamMemberRequest} addTeamMemberRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTeamMember: async (id: string, addTeamMemberRequest: AddTeamMemberRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addTeamMember', 'id', id)
            // verify required parameter 'addTeamMemberRequest' is not null or undefined
            assertParamExists('addTeamMember', 'addTeamMemberRequest', addTeamMemberRequest)
            const localVarPath = `/v1/teams/{id}/members`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addTeamMemberRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a pending request for the authenticated user to join a specific team.
         * @summary Request to Join Team
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJoinRequest: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createJoinRequest', 'id', id)
            const localVarPath = `/v1/teams/{id}/join-requests`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of pending join requests that the authenticated user is authorized to approve or reject.
         * @summary Get Admin Inbox
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminInbox: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/inbox`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a paginated list of members for a given team. Requires at least viewer access.
         * @summary List Team Members
         * @param {string} id 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTeamMembers: async (id: string, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listTeamMembers', 'id', id)
            const localVarPath = `/v1/teams/{id}/members`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes a user from a team. Requires admin privileges.
         * @summary Remove Team Member
         * @param {string} id 
         * @param {string} userID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeTeamMember: async (id: string, userID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('removeTeamMember', 'id', id)
            // verify required parameter 'userID' is not null or undefined
            assertParamExists('removeTeamMember', 'userID', userID)
            const localVarPath = `/v1/teams/{id}/members/{userID}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"userID"}}`, encodeURIComponent(String(userID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Approves or rejects a pending join request.
         * @summary Resolve Join Request
         * @param {string} id 
         * @param {ResolveJoinRequestRequest} resolveJoinRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resolveJoinRequest: async (id: string, resolveJoinRequestRequest: ResolveJoinRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('resolveJoinRequest', 'id', id)
            // verify required parameter 'resolveJoinRequestRequest' is not null or undefined
            assertParamExists('resolveJoinRequest', 'resolveJoinRequestRequest', resolveJoinRequestRequest)
            const localVarPath = `/v1/join-requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resolveJoinRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a team member\'s role. Requires team admin privileges.
         * @summary Update Team Member Role
         * @param {string} id 
         * @param {string} userID 
         * @param {UpdateTeamMemberRoleRequest} updateTeamMemberRoleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeamMemberRole: async (id: string, userID: string, updateTeamMemberRoleRequest: UpdateTeamMemberRoleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTeamMemberRole', 'id', id)
            // verify required parameter 'userID' is not null or undefined
            assertParamExists('updateTeamMemberRole', 'userID', userID)
            // verify required parameter 'updateTeamMemberRoleRequest' is not null or undefined
            assertParamExists('updateTeamMemberRole', 'updateTeamMemberRoleRequest', updateTeamMemberRoleRequest)
            const localVarPath = `/v1/teams/{id}/members/{userID}/role`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"userID"}}`, encodeURIComponent(String(userID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTeamMemberRoleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeamMembershipsApi - functional programming interface
 * @export
 */
export const TeamMembershipsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeamMembershipsApiAxiosParamCreator(configuration)
    return {
        /**
         * Adds a user to a team. Requires admin privileges.
         * @summary Add Team Member
         * @param {string} id 
         * @param {AddTeamMemberRequest} addTeamMemberRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTeamMember(id: string, addTeamMemberRequest: AddTeamMemberRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTeamMember(id, addTeamMemberRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembershipsApi.addTeamMember']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a pending request for the authenticated user to join a specific team.
         * @summary Request to Join Team
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJoinRequest(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeamJoinRequest>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJoinRequest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembershipsApi.createJoinRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a list of pending join requests that the authenticated user is authorized to approve or reject.
         * @summary Get Admin Inbox
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdminInbox(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAdminInbox200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdminInbox(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembershipsApi.getAdminInbox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a paginated list of members for a given team. Requires at least viewer access.
         * @summary List Team Members
         * @param {string} id 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTeamMembers(id: string, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTeamMembers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTeamMembers(id, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembershipsApi.listTeamMembers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Removes a user from a team. Requires admin privileges.
         * @summary Remove Team Member
         * @param {string} id 
         * @param {string} userID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeTeamMember(id: string, userID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeTeamMember(id, userID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembershipsApi.removeTeamMember']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Approves or rejects a pending join request.
         * @summary Resolve Join Request
         * @param {string} id 
         * @param {ResolveJoinRequestRequest} resolveJoinRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resolveJoinRequest(id: string, resolveJoinRequestRequest: ResolveJoinRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeamJoinRequest>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resolveJoinRequest(id, resolveJoinRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembershipsApi.resolveJoinRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates a team member\'s role. Requires team admin privileges.
         * @summary Update Team Member Role
         * @param {string} id 
         * @param {string} userID 
         * @param {UpdateTeamMemberRoleRequest} updateTeamMemberRoleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTeamMemberRole(id: string, userID: string, updateTeamMemberRoleRequest: UpdateTeamMemberRoleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateTeamMemberRole200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTeamMemberRole(id, userID, updateTeamMemberRoleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembershipsApi.updateTeamMemberRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TeamMembershipsApi - factory interface
 * @export
 */
export const TeamMembershipsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeamMembershipsApiFp(configuration)
    return {
        /**
         * Adds a user to a team. Requires admin privileges.
         * @summary Add Team Member
         * @param {string} id 
         * @param {AddTeamMemberRequest} addTeamMemberRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTeamMember(id: string, addTeamMemberRequest: AddTeamMemberRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addTeamMember(id, addTeamMemberRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a pending request for the authenticated user to join a specific team.
         * @summary Request to Join Team
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJoinRequest(id: string, options?: RawAxiosRequestConfig): AxiosPromise<TeamJoinRequest> {
            return localVarFp.createJoinRequest(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of pending join requests that the authenticated user is authorized to approve or reject.
         * @summary Get Admin Inbox
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminInbox(options?: RawAxiosRequestConfig): AxiosPromise<GetAdminInbox200Response> {
            return localVarFp.getAdminInbox(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a paginated list of members for a given team. Requires at least viewer access.
         * @summary List Team Members
         * @param {string} id 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTeamMembers(id: string, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListTeamMembers200Response> {
            return localVarFp.listTeamMembers(id, page, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes a user from a team. Requires admin privileges.
         * @summary Remove Team Member
         * @param {string} id 
         * @param {string} userID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeTeamMember(id: string, userID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeTeamMember(id, userID, options).then((request) => request(axios, basePath));
        },
        /**
         * Approves or rejects a pending join request.
         * @summary Resolve Join Request
         * @param {string} id 
         * @param {ResolveJoinRequestRequest} resolveJoinRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resolveJoinRequest(id: string, resolveJoinRequestRequest: ResolveJoinRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeamJoinRequest> {
            return localVarFp.resolveJoinRequest(id, resolveJoinRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a team member\'s role. Requires team admin privileges.
         * @summary Update Team Member Role
         * @param {string} id 
         * @param {string} userID 
         * @param {UpdateTeamMemberRoleRequest} updateTeamMemberRoleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeamMemberRole(id: string, userID: string, updateTeamMemberRoleRequest: UpdateTeamMemberRoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateTeamMemberRole200Response> {
            return localVarFp.updateTeamMemberRole(id, userID, updateTeamMemberRoleRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TeamMembershipsApi - interface
 * @export
 * @interface TeamMembershipsApi
 */
export interface TeamMembershipsApiInterface {
    /**
     * Adds a user to a team. Requires admin privileges.
     * @summary Add Team Member
     * @param {string} id 
     * @param {AddTeamMemberRequest} addTeamMemberRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApiInterface
     */
    addTeamMember(id: string, addTeamMemberRequest: AddTeamMemberRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Creates a pending request for the authenticated user to join a specific team.
     * @summary Request to Join Team
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApiInterface
     */
    createJoinRequest(id: string, options?: RawAxiosRequestConfig): AxiosPromise<TeamJoinRequest>;

    /**
     * Returns a list of pending join requests that the authenticated user is authorized to approve or reject.
     * @summary Get Admin Inbox
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApiInterface
     */
    getAdminInbox(options?: RawAxiosRequestConfig): AxiosPromise<GetAdminInbox200Response>;

    /**
     * Returns a paginated list of members for a given team. Requires at least viewer access.
     * @summary List Team Members
     * @param {string} id 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApiInterface
     */
    listTeamMembers(id: string, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListTeamMembers200Response>;

    /**
     * Removes a user from a team. Requires admin privileges.
     * @summary Remove Team Member
     * @param {string} id 
     * @param {string} userID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApiInterface
     */
    removeTeamMember(id: string, userID: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Approves or rejects a pending join request.
     * @summary Resolve Join Request
     * @param {string} id 
     * @param {ResolveJoinRequestRequest} resolveJoinRequestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApiInterface
     */
    resolveJoinRequest(id: string, resolveJoinRequestRequest: ResolveJoinRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeamJoinRequest>;

    /**
     * Updates a team member\'s role. Requires team admin privileges.
     * @summary Update Team Member Role
     * @param {string} id 
     * @param {string} userID 
     * @param {UpdateTeamMemberRoleRequest} updateTeamMemberRoleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApiInterface
     */
    updateTeamMemberRole(id: string, userID: string, updateTeamMemberRoleRequest: UpdateTeamMemberRoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateTeamMemberRole200Response>;

}

/**
 * TeamMembershipsApi - object-oriented interface
 * @export
 * @class TeamMembershipsApi
 * @extends {BaseAPI}
 */
export class TeamMembershipsApi extends BaseAPI implements TeamMembershipsApiInterface {
    /**
     * Adds a user to a team. Requires admin privileges.
     * @summary Add Team Member
     * @param {string} id 
     * @param {AddTeamMemberRequest} addTeamMemberRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApi
     */
    public addTeamMember(id: string, addTeamMemberRequest: AddTeamMemberRequest, options?: RawAxiosRequestConfig) {
        return TeamMembershipsApiFp(this.configuration).addTeamMember(id, addTeamMemberRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a pending request for the authenticated user to join a specific team.
     * @summary Request to Join Team
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApi
     */
    public createJoinRequest(id: string, options?: RawAxiosRequestConfig) {
        return TeamMembershipsApiFp(this.configuration).createJoinRequest(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of pending join requests that the authenticated user is authorized to approve or reject.
     * @summary Get Admin Inbox
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApi
     */
    public getAdminInbox(options?: RawAxiosRequestConfig) {
        return TeamMembershipsApiFp(this.configuration).getAdminInbox(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a paginated list of members for a given team. Requires at least viewer access.
     * @summary List Team Members
     * @param {string} id 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApi
     */
    public listTeamMembers(id: string, page?: number, options?: RawAxiosRequestConfig) {
        return TeamMembershipsApiFp(this.configuration).listTeamMembers(id, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes a user from a team. Requires admin privileges.
     * @summary Remove Team Member
     * @param {string} id 
     * @param {string} userID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApi
     */
    public removeTeamMember(id: string, userID: string, options?: RawAxiosRequestConfig) {
        return TeamMembershipsApiFp(this.configuration).removeTeamMember(id, userID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Approves or rejects a pending join request.
     * @summary Resolve Join Request
     * @param {string} id 
     * @param {ResolveJoinRequestRequest} resolveJoinRequestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApi
     */
    public resolveJoinRequest(id: string, resolveJoinRequestRequest: ResolveJoinRequestRequest, options?: RawAxiosRequestConfig) {
        return TeamMembershipsApiFp(this.configuration).resolveJoinRequest(id, resolveJoinRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a team member\'s role. Requires team admin privileges.
     * @summary Update Team Member Role
     * @param {string} id 
     * @param {string} userID 
     * @param {UpdateTeamMemberRoleRequest} updateTeamMemberRoleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamMembershipsApi
     */
    public updateTeamMemberRole(id: string, userID: string, updateTeamMemberRoleRequest: UpdateTeamMemberRoleRequest, options?: RawAxiosRequestConfig) {
        return TeamMembershipsApiFp(this.configuration).updateTeamMemberRole(id, userID, updateTeamMemberRoleRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

