/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APIKeyCreatedResponse
 */
export interface APIKeyCreatedResponse {
    /**
     * Unique API Key identifier.
     * @type {string}
     * @memberof APIKeyCreatedResponse
     */
    'id': string;
    /**
     * Human-readable name of the key.
     * @type {string}
     * @memberof APIKeyCreatedResponse
     */
    'name': string;
    /**
     * The fully generated secure raw API Key string. This is returned ONLY ONCE.
     * @type {string}
     * @memberof APIKeyCreatedResponse
     */
    'key': string;
    /**
     * Identifying prefix of the key.
     * @type {string}
     * @memberof APIKeyCreatedResponse
     */
    'key_prefix': string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyCreatedResponse
     */
    'operation': string;
    /**
     * Timestamp of creation.
     * @type {string}
     * @memberof APIKeyCreatedResponse
     */
    'created_at': string;
}

