/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APIKey
 */
export interface APIKey {
    /**
     * Unique API Key identifier.
     * @type {string}
     * @memberof APIKey
     */
    'id': string;
    /**
     * Human-readable name given to the API key.
     * @type {string}
     * @memberof APIKey
     */
    'name': string;
    /**
     * UUID of the organization.
     * @type {string}
     * @memberof APIKey
     */
    'org_id': string;
    /**
     * Optional UUID of the team.
     * @type {string}
     * @memberof APIKey
     */
    'team_id'?: string;
    /**
     * First characters of the API Key used for visual identification.
     * @type {string}
     * @memberof APIKey
     */
    'key_prefix': string;
    /**
     * The scope of operations.
     * @type {string}
     * @memberof APIKey
     */
    'operation': APIKeyOperationEnum;
    /**
     * Timestamp when the API Key was created.
     * @type {string}
     * @memberof APIKey
     */
    'created_at': string;
    /**
     * Timestamp when the API Key was last used. Null if never used.
     * @type {string}
     * @memberof APIKey
     */
    'last_used_at'?: string;
}

export const APIKeyOperationEnum = {
    ReadRender: 'read_render',
    All: 'all',
    Admin: 'admin'
} as const;

export type APIKeyOperationEnum = typeof APIKeyOperationEnum[keyof typeof APIKeyOperationEnum];


