/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PromptVersion } from './prompt-version';

/**
 * 
 * @export
 * @interface ListVersions200Response
 */
export interface ListVersions200Response {
    /**
     * 
     * @type {Array<PromptVersion>}
     * @memberof ListVersions200Response
     */
    'versions': Array<PromptVersion>;
}

