/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Prompt
 */
export interface Prompt {
    /**
     * Unique identifier.
     * @type {string}
     * @memberof Prompt
     */
    'id': string;
    /**
     * Unique identifier of the team.
     * @type {string}
     * @memberof Prompt
     */
    'team_id': string;
    /**
     * Unique slug within the team.
     * @type {string}
     * @memberof Prompt
     */
    'slug': string;
    /**
     * Name of the prompt container.
     * @type {string}
     * @memberof Prompt
     */
    'name': string;
    /**
     * Brief summary explaining the prompt purpose.
     * @type {string}
     * @memberof Prompt
     */
    'description': string;
    /**
     * Current status of the prompt container (active, archived).
     * @type {string}
     * @memberof Prompt
     */
    'status': PromptStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    'updated_at': string;
}

export const PromptStatusEnum = {
    Active: 'active',
    Archived: 'archived'
} as const;

export type PromptStatusEnum = typeof PromptStatusEnum[keyof typeof PromptStatusEnum];


