/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PromptPayload
 */
export interface PromptPayload {
    /**
     * Unique payload identifier.
     * @type {string}
     * @memberof PromptPayload
     */
    'id': string;
    /**
     * Reference to parent Prompt ID.
     * @type {string}
     * @memberof PromptPayload
     */
    'prompt_id': string;
    /**
     * Optional name for this sample payload.
     * @type {string}
     * @memberof PromptPayload
     */
    'name'?: string;
    /**
     * Standard JSON object containing variable names and sample values.
     * @type {object}
     * @memberof PromptPayload
     */
    'variables': object;
    /**
     * 
     * @type {string}
     * @memberof PromptPayload
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof PromptPayload
     */
    'updated_at': string;
}

