/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PromptVersion
 */
export interface PromptVersion {
    /**
     * Unique version identifier.
     * @type {string}
     * @memberof PromptVersion
     */
    'id': string;
    /**
     * Reference to parent Prompt ID.
     * @type {string}
     * @memberof PromptVersion
     */
    'prompt_id': string;
    /**
     * Incrementing sequence number of the version.
     * @type {number}
     * @memberof PromptVersion
     */
    'version': number;
    /**
     * The template syntax code with Go template parameters.
     * @type {string}
     * @memberof PromptVersion
     */
    'template': string;
    /**
     * Active lifecycle status of this template version.
     * @type {string}
     * @memberof PromptVersion
     */
    'status': PromptVersionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PromptVersion
     */
    'created_at': string;
    /**
     * Timestamp when status was set to live. Null if draft.
     * @type {string}
     * @memberof PromptVersion
     */
    'published_at': string;
    /**
     * List of tag strings attached to this version.
     * @type {Array<string>}
     * @memberof PromptVersion
     */
    'tags': Array<string>;
}

export const PromptVersionStatusEnum = {
    Draft: 'draft',
    Stable: 'stable',
    Live: 'live',
    Archived: 'archived'
} as const;

export type PromptVersionStatusEnum = typeof PromptVersionStatusEnum[keyof typeof PromptVersionStatusEnum];


