/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeamJoinRequest
 */
export interface TeamJoinRequest {
    /**
     * 
     * @type {string}
     * @memberof TeamJoinRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamJoinRequest
     */
    'team_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamJoinRequest
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamJoinRequest
     */
    'status': TeamJoinRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TeamJoinRequest
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof TeamJoinRequest
     */
    'updated_at': string;
}

export const TeamJoinRequestStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected'
} as const;

export type TeamJoinRequestStatusEnum = typeof TeamJoinRequestStatusEnum[keyof typeof TeamJoinRequestStatusEnum];


