/* tslint:disable */
/* eslint-disable */
/**
 * px0 API
 * Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * Unique user identifier.
     * @type {string}
     * @memberof User
     */
    'id': string;
    /**
     * Email address of the user.
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * Whether the user\'s email has been verified.
     * @type {boolean}
     * @memberof User
     */
    'is_verified': boolean;
    /**
     * Whether the user is an admin.
     * @type {boolean}
     * @memberof User
     */
    'is_admin': boolean;
    /**
     * Timestamp when the user was created.
     * @type {string}
     * @memberof User
     */
    'created_at': string;
}

